os: linux

language: go

go:
  - 1.14.x

service:
  - postresql

env:
  APP_DB_NAME=postgres
  APP_DB_USERNAME=postgres
  APP_DB_PASSWORD=1234


script:
  # Test the code
  - go test -v ./...
  # Build the code
  - CGO_ENABLED=0 GOARCH=amd64 go build -o demo